### ISSUE TITLE
Demo gets corrupted when the demo have custom weapons.

### ISSUE THREAD

**Issue by Politohh** [Caball009/Call-of-Duty-4-X-Demo-Tool#2]
Hello,

i m not exactly sure if it is the exact reason but after many tests, thats my conlusion.

IF you play a cod4x server that have custom added weapons, after converting the demo for 1.7 client /iw3xo, the demo doesnt work anymore even though u have the files from the server.
error is :
![image](https://github.com/Caball009/Call-of-Duty-4-X-Demo-Tool/assets/105368198/1b0771e9-95ef-4346-a3c5-aabdd795838a)

**Comment by Caball009** [comment]
This not related to the conversion to v1.7. This may happen when a server is heavily modded even though there's no explicit mod download requirement. In such cases even playing the original demo with the right CoD4X client version will give the same or similar error.

Basically, the way the server is modded results in corrupted demos; not so much so that it's unfixable, but not something I intend to implement.
